repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        name: Ruff linter
        entry: ruff check inspect_weave tests
        language: python
        types: [python]
        pass_filenames: false

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.4
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: mypy
        name: Mypy type checker
        language: python
        entry: mypy
        types: [python]
        pass_filenames: false
        args: [inspect_weave]