repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        name: Ruff linter
        entry: ruff check .
        language: python
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        name: Mypy type checker
        language: python
        types: [python]
        pass_filenames: false
        args: [inspect_weave]