[project]
name = "inspect_weave"
version = "0.1.0"
authors = [
  { name="MARS 3.0 (Daniel Polatajko, Matan Shtepel, Qi Guo)", email="danielpolatajko@gmail.com" },
]
description = "InspectAI <-> Weights and Biases Weave integration"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/DanielPolatajko/inspect_weave"
Issues = "https://github.com/DanielPolatajko/inspect_weave/issues"

[build-system]
requires = ["setuptools >= 80.0.0"]
build-backend = "setuptools.build_meta"

[project.entry-points.inspect_ai]
inspect_weave = "inspect_weave._registry"