models:
  enabled: true
  project: test-project
  entity: danielpolatajko-mars
  files:
    - "inspect-weave-settings.yaml"

weave:
  enabled: true
  project: test-project
  entity: danielpolatajko-mars